### ISSUE TITLE
object detector

### ISSUE THREAD

**Issue by liuc-v** [zhihou7/VCL#11]
Thnaks for you enlightening work.
The object detection result you provide in [VCL](https://github.com/zhihou7/VCL/) is https://drive.google.com/file/d/1QI1kcZJqI-ym6AGQ2swwp4CKb39uLf-4/view. But the object detection result only contains 71 kinds of objects.Shouldn't it be 80?

**Comment by zhihou7** [comment]
hi,
thanks for your comment. It is interesting. I did not notice this problem. It seems like some objects are missed by the object detector? e.g., the object detector is finetued on HICO-DET, but the distribution of those objects on HICO is seriously long-tailed. I guess the detector fails to detect some kinds of objects.

**Comment by liuc-v** [comment]
cell_phone
frisbee
microwave
remote
spoon
stop_sign
suitcase
toaster
umbrella 
these are the missed object

**Comment by zhihou7** [comment]
Do you mean miss to detect those objects or the detector is unable to detect those?
Best,

**Comment by liuc-v** [comment]
I only looked at the pkl file(https://drive.google.com/file/d/1QI1kcZJqI-ym6AGQ2swwp4CKb39uLf-4/view) you provided, and these objects did not appear in the pkl file.

**Comment by zhihou7** [comment]
thanks, I think it is because the detector fails to detect the corresponding objects in those images.
