### ISSUE TITLE
Tensor 'sp:0' shape mismatch

### ISSUE THREAD

**Issue by anqingjianke** [zhihou7/VCL#2]
Hello:
    You job is so cool, I am very glad to try this new project.
    I trained a model by coco dataset with Res50. But when I run "Test_VCL_ResNet_VCOCO.py", error will be called. Like:
        
        "VCL_ResNet50_VCOCO doesn't support pool5_HO
        ......
        Traceback (most recent call last):
             File "tools/Test_VCL_ResNet_VCOCO.py", line 88, in <module>
                 net.create_architecture(False)
               >>/lib/networks/ResNet50_VCOCO.py", line 418, in create_architecture
                 self.build_network(is_training)
               >>/lib/networks/HOI.py", line 169, in build_network
                 fc7_HO_raw = self.res5_ho(pool5_HO, is_training, 'res5')
               >>/lib/networks/HOI.py", line 66, in res5_ho
                 scope=self.scope)
        ...
        AttributeError: 'NoneType' object has no attribute 'get_shape' "

    Now I have no idea. So could you help me?

**Comment by zhihou7** [comment]
Sorry for getting back to you late. 
The strategies in My code depends on model_name (containing many args) very much. This could lead to some problems although it helps me to compare different models directly.

Besides, we do not conduct much experiment on V-COCO because it is not long-tailed.

**Comment by anqingjianke** [comment]
Thank you for your reply.

>Besides, we do not conduct much experiment on V-COCO because it is not long-tailed.

So did you finished testing models on V-COCO? Now I encounter a new problem:

    ./lib/networks/Resnet50_VCOCO.py line 549
        "cls_prob_HO = sess.run([self.predictions["cls_prob_HO"]], feed_dict=feed_dict)"

Here will feed back 
    "ValueError: Cannot feed value of shape (1, 64, 64, 2) for Tensor 'sp:0', which has shape '(?, 64, 64, 3)'"

I find this function is called in  ./lib/models/test_VCOCO.py line 58-59
    "blobs['sp']      = Get_next_sp(Human_out[2], Object[2]).reshape(1, 64, 64, 2)
                    prediction_HO  = net.test_image_HO(sess, im_orig, blobs)"

I feel confused about "Tensor shape mismatch". Could you give me some tips?

**Comment by zhihou7** [comment]
Could you provide the command?

**Comment by zhihou7** [comment]
Thanks for your reply. 
I have fixed the bug in Test_VCL_ResNet_VCOCO.py and updated the code.

Sorry for bringing the trouble.

**Comment by zhihou7** [comment]
'(?, 64, 64, 3)' here 3 is for the additional feature pose from other released HOI code. It is not very effective and I do not use this in my paper. I forget remove this in evaluation code. Thank you for pointing out my mistakes. I also fix the evaluation code for HICO-DET. You can directly use the evaluation code from iCAN. I just optimize a bit the running speed of the evaluation code.

**Comment by anqingjianke** [comment]
OK, it works. Thanks a lot!
