### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by bitwangdan** [zhihou7/VCL#3]
![image](https://user-images.githubusercontent.com/18326564/91516467-25c24200-e91e-11ea-8740-5c74be59be49.png)

hi, when  i run "python tools/Test_ResNet_VCOCO.py --num_iteration 200000", an error has occurred, Have you ever experienced this?
@zhihou7

**Comment by xxxzhi** [comment]
You should set the model rightly. Besides, pull the code and try again. I have updated the code. See  #2 

In my experiment, you must add union or humans in the model name. union is a bit better. like: VCL_union_multi_ml1_l05_t3_rew_aug5_3_new_VCOCO_test.

This strategy is a bit confused. But it helps me to conduct ablation study to compared the different methods.
