### ISSUE TITLE
Number of parameters in the model?

### ISSUE THREAD

**Issue by mohita-chowdhury** [zhihou7/VCL#6]
Hi,
First of all, kudos to the great work!

I was wondering if you have an idea on the number of parameters (trainable and total) used by your model? I could probably dig into your code to find that but it would help if you have it already!

Looking forward to your reply! Thanks!

**Comment by zhihou7** [comment]
Sorry for getting you late. Thanks for your interest.
I have not stated this. The weights in the proposed network is resnet50 (first layer to resnet block 3), 2 resnet block 4 (human, object), Spatial pattern (two layers conv2d see below), two FCs for verb-object ( 4096- > 1024 -> 1024-> 600), two FCs for sp-human (5408+2048 -> 1024-> 1024 -> 600)


            conv1_sp      = slim.conv2d(self.spatial[:,:,:,0:2], 64, [5, 5], padding='VALID', scope='conv1_sp') # input : 64*64*2
            pool1_sp      = slim.max_pool2d(conv1_sp, [2, 2], scope='pool1_sp')
            conv2_sp      = slim.conv2d(pool1_sp,     32, [5, 5], padding='VALID', scope='conv2_sp')
            pool2_sp      = slim.max_pool2d(conv2_sp, [2, 2], scope='pool2_sp')
            pool2_flat_sp = slim.flatten(pool2_sp)

**Comment by zhihou7** [comment]
I think our model also contains a unique object detector (e.g. faster-rcnn).
