### ISSUE TITLE
About Preprocessed file

### ISSUE THREAD

**Issue by hutao568** [zhihou7/VCL#7]
Hello, I want to migrate your code to my project, but I don’t quite understand what Trainval_GT_VCOCO_obj.pkl and Trainval_Neg_VCOCO_obj.pkl in your code mean, and how to generate the above format using hico-det raw data

你好，我想把您的代码迁移到我的项目中，但是我不是很明白您代码里的Trainval_GT_VCOCO_obj.pkl和Trainval_Neg_VCOCO_obj.pkl是什么意思，使用hico-det原始数据如何生成上述格式

**Comment by zhihou7** [comment]
Sorry for the confusing file name. 

The "_obj" in the file means we add the COCO object category id (80 classes) in this file.  The obj category id is in the last row for each HOI instance.

**Comment by hutao568** [comment]
Thanks, you let me understand the meaning of _obj, I found my answer here
https://github.com/vt-vl-lab/iCAN/issues/7
